variable "access_key" {
  type = string
}

variable "secret_key" {
  type = string
}

variable "ingressCIDRblock" {
  type    = list(any)
  default = ["0.0.0.0/0"]
} 

variable "egressCIDRblock" {
  type    = list(any)
  default = ["0.0.0.0/0"]
} 

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}